export function ClipboardSetText(arg1) { return new Promise(() => {}) }
export function BrowserOpenURL(arg1) { return new Promise(() => {}) }
export function EventsOn(arg1) { return new Promise(() => {}) }
export function AddRepo() { return new Promise(() => {}) }
export function AddTag(arg1, arg2, arg3, arg4, arg5) { return new Promise(() => {}) }
export function BranchExists(arg1) { return new Promise(() => {}) }
export function CheckoutCommit(arg1) { return new Promise(() => {}) }
export function CreateBranch(arg1, arg2, arg3) { return new Promise(() => {}) }
export function DeleteBranch(arg1, arg2, arg3) { return new Promise(() => {}) }
export function DeleteRemoteBranch(arg1, arg2, arg3) { return new Promise(() => {}) }
export function DeleteTag(arg1) { return new Promise(() => {}) }
export function FetchRemote(arg1) { return new Promise(() => {}) }
export function GetBranches() { return new Promise(() => {}) }
export function GetCommitDetails(arg1) { return new Promise(() => {}) }
export function GetCommitDiffSummary(arg1) { return new Promise(() => {}) }
export function GetCommitList(arg1, arg2) { return new Promise(() => {}) }
export function GetCommitSignature(arg1) { return new Promise(() => {}) }
export function GetCommitsSignStatus(arg1, arg2) { return new Promise(() => {}) }
export function GetCurrentBranch() { return new Promise(() => {}) }
export function GetRemotes() { return new Promise(() => {}) }
export function GetRepos() { return new Promise(() => {}) }
export function GetSelectedRepo() { return new Promise(() => {}) }
export function GetSettings() { return new Promise(() => {}) }
export function GitListChanges() { return new Promise(() => {}) }
export function HardReset(arg1) { return new Promise(() => {}) }
export function MakeCommit(arg1, arg2) { return new Promise(() => {}) }
export function MergeCommit(arg1, arg2, arg3) { return new Promise(() => {}) }
export function MergeFastForward(arg1) { return new Promise(() => {}) }
export function MergeRebase(arg1) { return new Promise(() => {}) }
export function MergeSquash(arg1) { return new Promise(() => {}) }
export function NumBranches() { return new Promise(() => {}) }
export function NumMainBranchCommits() { return new Promise(() => {}) }
export function NumTags() { return new Promise(() => {}) }
export function PullBranch(arg1) { return new Promise(() => {}) }
export function PullRemote(arg1) { return new Promise(() => {}) }
export function PullRemoteBranch(arg1, arg2, arg3) { return new Promise(() => {}) }
export function PushBranch(arg1) { return new Promise(() => {}) }
export function PushRemote(arg1) { return new Promise(() => {}) }
export function PushTag(arg1) { return new Promise(() => {}) }
export function RebaseOnBranch(arg1) { return new Promise(() => {}) }
export function RemoveRepo(arg1) { return new Promise(() => {}) }
export function RenameBranch(arg1, arg2) { return new Promise(() => {}) }
export function ResetBranchToRemote(arg1) { return new Promise(() => {}) }
export function ResizeWindow() { return new Promise(() => {}) }
export function RevertCommit(arg1) { return new Promise(() => {}) }
export function SaveSettingsGui(arg1) { return new Promise(() => {}) }
export function StageAll() { return new Promise(() => {}) }
export function StageFile(arg1) { return new Promise(() => {}) }
export function SwitchBranch(arg1, arg2) { return new Promise(() => {}) }
export function UnstageAll() { return new Promise(() => {}) }
export function UnstageFile(arg1) { return new Promise(() => {}) }
export function UpdateMain(arg1) { return new Promise(() => {}) }
export function UpdateSelectedRepo(arg1) { return new Promise(() => {}) }
