on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Get version tag
        uses: little-core-labs/get-git-tag@v3.0.1
        id: version

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.5.1

      # darwin
      - name: Build for darwin
        if: matrix.platform == 'macos-latest'
        run: |
          wails build -platform darwin/universal

      - name: Create darwin package
        if: matrix.platform == 'macos-latest'
        run: |
          productbuild --component "build/bin/Ivy Git.app" "Ivy Git_${{ steps.version.outputs.tag }}_Darwin_Universal.pkg"

      - name: Upload darwin package
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: release-darwin
          path: IvyGit_${{ steps.version.outputs.tag }}_Darwin_*
          retention-days: 2

      # windows
      - name: Build for windows
        if: matrix.platform == 'windows-latest'
        run: |
          wails build -platform windows/amd64 -nsis
          Compress-Archive -Path "$PWD\build\bin\Ivy Git.exe" -DestinationPath "$PWD\IvyGit_${{ steps.version.outputs.tag }}_Windows_x86_64.zip"
          Rename-Item -Path "$PWD\build\bin\Ivy Git-amd64-installer.exe" -NewName "$PWD\IvyGit_${{ steps.version.outputs.tag }}_Windows_x86_64_installer.exe"

      - name: Upload windows zip and installer
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: release-windows
          path: IvyGit_${{ steps.version.outputs.tag }}_Windows_*
          retention-days: 2

  release:
    runs-on: ubuntu-latest
    needs: build
    name: Release
    steps:
      - name: Get version tag
        id: version
        run: echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Download all release pacakges
        uses: actions/download-artifact@v3
        id: artifact
        with:
          path: releases

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          draft: true
          prerelease: false
          files: |
            ${{steps.artifact.outputs.download-path}}/IvyGit_${{ steps.version.outputs.tag }}_Darwin_Universal.pkg
            ${{steps.artifact.outputs.download-path}}/IvyGit_${{ steps.version.outputs.tag }}_Windows_x86_64.zip
            ${{steps.artifact.outputs.download-path}}/IvyGit_${{ steps.version.outputs.tag }}_Windows_x86_64_installer.zip
